/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rideapp.publishride.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the bookings service. Represents a row in the &quot;Rideapp_bookings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.rideapp.publishride.model.impl.bookingsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.rideapp.publishride.model.impl.bookingsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bookings
 * @generated
 */
@ProviderType
public interface bookingsModel
	extends BaseModel<bookings>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bookings model instance should use the {@link bookings} interface instead.
	 */

	/**
	 * Returns the primary key of this bookings.
	 *
	 * @return the primary key of this bookings
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bookings.
	 *
	 * @param primaryKey the primary key of this bookings
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bookings ID of this bookings.
	 *
	 * @return the bookings ID of this bookings
	 */
	public long getBookingsId();

	/**
	 * Sets the bookings ID of this bookings.
	 *
	 * @param bookingsId the bookings ID of this bookings
	 */
	public void setBookingsId(long bookingsId);

	/**
	 * Returns the group ID of this bookings.
	 *
	 * @return the group ID of this bookings
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this bookings.
	 *
	 * @param groupId the group ID of this bookings
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this bookings.
	 *
	 * @return the company ID of this bookings
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this bookings.
	 *
	 * @param companyId the company ID of this bookings
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this bookings.
	 *
	 * @return the user ID of this bookings
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this bookings.
	 *
	 * @param userId the user ID of this bookings
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bookings.
	 *
	 * @return the user uuid of this bookings
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this bookings.
	 *
	 * @param userUuid the user uuid of this bookings
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this bookings.
	 *
	 * @return the user name of this bookings
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this bookings.
	 *
	 * @param userName the user name of this bookings
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this bookings.
	 *
	 * @return the create date of this bookings
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this bookings.
	 *
	 * @param createDate the create date of this bookings
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bookings.
	 *
	 * @return the modified date of this bookings
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bookings.
	 *
	 * @param modifiedDate the modified date of this bookings
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the booking date of this bookings.
	 *
	 * @return the booking date of this bookings
	 */
	public Date getBookingDate();

	/**
	 * Sets the booking date of this bookings.
	 *
	 * @param bookingDate the booking date of this bookings
	 */
	public void setBookingDate(Date bookingDate);

	/**
	 * Returns the booked seats of this bookings.
	 *
	 * @return the booked seats of this bookings
	 */
	public int getBookedSeats();

	/**
	 * Sets the booked seats of this bookings.
	 *
	 * @param bookedSeats the booked seats of this bookings
	 */
	public void setBookedSeats(int bookedSeats);

	/**
	 * Returns the total price of this bookings.
	 *
	 * @return the total price of this bookings
	 */
	public float getTotalPrice();

	/**
	 * Sets the total price of this bookings.
	 *
	 * @param totalPrice the total price of this bookings
	 */
	public void setTotalPrice(float totalPrice);

	/**
	 * Returns the rides ID of this bookings.
	 *
	 * @return the rides ID of this bookings
	 */
	public long getRidesId();

	/**
	 * Sets the rides ID of this bookings.
	 *
	 * @param ridesId the rides ID of this bookings
	 */
	public void setRidesId(long ridesId);

	@Override
	public bookings cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}