/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rideapp.publishride.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the rides service. Represents a row in the &quot;Rideapp_rides&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.rideapp.publishride.model.impl.ridesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.rideapp.publishride.model.impl.ridesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rides
 * @generated
 */
@ProviderType
public interface ridesModel
	extends BaseModel<rides>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rides model instance should use the {@link rides} interface instead.
	 */

	/**
	 * Returns the primary key of this rides.
	 *
	 * @return the primary key of this rides
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rides.
	 *
	 * @param primaryKey the primary key of this rides
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rides ID of this rides.
	 *
	 * @return the rides ID of this rides
	 */
	public long getRidesId();

	/**
	 * Sets the rides ID of this rides.
	 *
	 * @param ridesId the rides ID of this rides
	 */
	public void setRidesId(long ridesId);

	/**
	 * Returns the group ID of this rides.
	 *
	 * @return the group ID of this rides
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this rides.
	 *
	 * @param groupId the group ID of this rides
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this rides.
	 *
	 * @return the company ID of this rides
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this rides.
	 *
	 * @param companyId the company ID of this rides
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this rides.
	 *
	 * @return the user ID of this rides
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this rides.
	 *
	 * @param userId the user ID of this rides
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this rides.
	 *
	 * @return the user uuid of this rides
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this rides.
	 *
	 * @param userUuid the user uuid of this rides
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this rides.
	 *
	 * @return the user name of this rides
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this rides.
	 *
	 * @param userName the user name of this rides
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this rides.
	 *
	 * @return the create date of this rides
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this rides.
	 *
	 * @param createDate the create date of this rides
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this rides.
	 *
	 * @return the modified date of this rides
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this rides.
	 *
	 * @param modifiedDate the modified date of this rides
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the leaving location of this rides.
	 *
	 * @return the leaving location of this rides
	 */
	@AutoEscape
	public String getLeavingLocation();

	/**
	 * Sets the leaving location of this rides.
	 *
	 * @param leavingLocation the leaving location of this rides
	 */
	public void setLeavingLocation(String leavingLocation);

	/**
	 * Returns the heading location of this rides.
	 *
	 * @return the heading location of this rides
	 */
	@AutoEscape
	public String getHeadingLocation();

	/**
	 * Sets the heading location of this rides.
	 *
	 * @param headingLocation the heading location of this rides
	 */
	public void setHeadingLocation(String headingLocation);

	/**
	 * Returns the arival date of this rides.
	 *
	 * @return the arival date of this rides
	 */
	public Date getArivalDate();

	/**
	 * Sets the arival date of this rides.
	 *
	 * @param arivalDate the arival date of this rides
	 */
	public void setArivalDate(Date arivalDate);

	/**
	 * Returns the available seats of this rides.
	 *
	 * @return the available seats of this rides
	 */
	public int getAvailableSeats();

	/**
	 * Sets the available seats of this rides.
	 *
	 * @param availableSeats the available seats of this rides
	 */
	public void setAvailableSeats(int availableSeats);

	/**
	 * Returns the comfort level of this rides.
	 *
	 * @return the comfort level of this rides
	 */
	@AutoEscape
	public String getComfortLevel();

	/**
	 * Sets the comfort level of this rides.
	 *
	 * @param comfortLevel the comfort level of this rides
	 */
	public void setComfortLevel(String comfortLevel);

	/**
	 * Returns the price of this rides.
	 *
	 * @return the price of this rides
	 */
	public float getPrice();

	/**
	 * Sets the price of this rides.
	 *
	 * @param price the price of this rides
	 */
	public void setPrice(float price);

	@Override
	public rides cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}