/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rideapp.publishride.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the vehicals service. Represents a row in the &quot;Rideapp_vehicals&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.rideapp.publishride.model.impl.vehicalsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.rideapp.publishride.model.impl.vehicalsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see vehicals
 * @generated
 */
@ProviderType
public interface vehicalsModel
	extends BaseModel<vehicals>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vehicals model instance should use the {@link vehicals} interface instead.
	 */

	/**
	 * Returns the primary key of this vehicals.
	 *
	 * @return the primary key of this vehicals
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vehicals.
	 *
	 * @param primaryKey the primary key of this vehicals
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vehicals ID of this vehicals.
	 *
	 * @return the vehicals ID of this vehicals
	 */
	public long getVehicalsId();

	/**
	 * Sets the vehicals ID of this vehicals.
	 *
	 * @param vehicalsId the vehicals ID of this vehicals
	 */
	public void setVehicalsId(long vehicalsId);

	/**
	 * Returns the group ID of this vehicals.
	 *
	 * @return the group ID of this vehicals
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this vehicals.
	 *
	 * @param groupId the group ID of this vehicals
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vehicals.
	 *
	 * @return the company ID of this vehicals
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vehicals.
	 *
	 * @param companyId the company ID of this vehicals
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vehicals.
	 *
	 * @return the user ID of this vehicals
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vehicals.
	 *
	 * @param userId the user ID of this vehicals
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vehicals.
	 *
	 * @return the user uuid of this vehicals
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this vehicals.
	 *
	 * @param userUuid the user uuid of this vehicals
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vehicals.
	 *
	 * @return the user name of this vehicals
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vehicals.
	 *
	 * @param userName the user name of this vehicals
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vehicals.
	 *
	 * @return the create date of this vehicals
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vehicals.
	 *
	 * @param createDate the create date of this vehicals
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vehicals.
	 *
	 * @return the modified date of this vehicals
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vehicals.
	 *
	 * @param modifiedDate the modified date of this vehicals
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the car model of this vehicals.
	 *
	 * @return the car model of this vehicals
	 */
	@AutoEscape
	public String getCarModel();

	/**
	 * Sets the car model of this vehicals.
	 *
	 * @param carModel the car model of this vehicals
	 */
	public void setCarModel(String carModel);

	/**
	 * Returns the plate number of this vehicals.
	 *
	 * @return the plate number of this vehicals
	 */
	@AutoEscape
	public String getPlateNumber();

	/**
	 * Sets the plate number of this vehicals.
	 *
	 * @param plateNumber the plate number of this vehicals
	 */
	public void setPlateNumber(String plateNumber);

	/**
	 * Returns the capacity of this vehicals.
	 *
	 * @return the capacity of this vehicals
	 */
	public int getCapacity();

	/**
	 * Sets the capacity of this vehicals.
	 *
	 * @param capacity the capacity of this vehicals
	 */
	public void setCapacity(int capacity);

	/**
	 * Returns the comfort level of this vehicals.
	 *
	 * @return the comfort level of this vehicals
	 */
	@AutoEscape
	public String getComfortLevel();

	/**
	 * Sets the comfort level of this vehicals.
	 *
	 * @param comfortLevel the comfort level of this vehicals
	 */
	public void setComfortLevel(String comfortLevel);

	@Override
	public vehicals cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}