/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rideapp.publishride.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.rideapp.publishride.model.locations;
import com.rideapp.publishride.model.locationsModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the locations service. Represents a row in the &quot;Rideapp_locations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>locationsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link locationsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see locationsImpl
 * @generated
 */
@JSON(strict = true)
public class locationsModelImpl
	extends BaseModelImpl<locations> implements locationsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a locations model instance should use the <code>locations</code> interface instead.
	 */
	public static final String TABLE_NAME = "Rideapp_locations";

	public static final Object[][] TABLE_COLUMNS = {
		{"locationsId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"latitude", Types.DOUBLE}, {"longitude", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("locationsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("latitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("longitude", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Rideapp_locations (locationsId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,latitude DOUBLE,longitude DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table Rideapp_locations";

	public static final String ORDER_BY_JPQL =
		" ORDER BY locations.locationsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Rideapp_locations.locationsId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOCATIONSID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public locationsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _locationsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLocationsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _locationsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return locations.class;
	}

	@Override
	public String getModelClassName() {
		return locations.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<locations, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<locations, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<locations, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((locations)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<locations, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<locations, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(locations)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<locations, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<locations, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<locations, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<locations, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<locations, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<locations, Object>>();
		Map<String, BiConsumer<locations, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<locations, ?>>();

		attributeGetterFunctions.put("locationsId", locations::getLocationsId);
		attributeSetterBiConsumers.put(
			"locationsId",
			(BiConsumer<locations, Long>)locations::setLocationsId);
		attributeGetterFunctions.put("groupId", locations::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<locations, Long>)locations::setGroupId);
		attributeGetterFunctions.put("companyId", locations::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<locations, Long>)locations::setCompanyId);
		attributeGetterFunctions.put("userId", locations::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<locations, Long>)locations::setUserId);
		attributeGetterFunctions.put("userName", locations::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<locations, String>)locations::setUserName);
		attributeGetterFunctions.put("createDate", locations::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<locations, Date>)locations::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", locations::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<locations, Date>)locations::setModifiedDate);
		attributeGetterFunctions.put("name", locations::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<locations, String>)locations::setName);
		attributeGetterFunctions.put("latitude", locations::getLatitude);
		attributeSetterBiConsumers.put(
			"latitude", (BiConsumer<locations, Double>)locations::setLatitude);
		attributeGetterFunctions.put("longitude", locations::getLongitude);
		attributeSetterBiConsumers.put(
			"longitude",
			(BiConsumer<locations, Double>)locations::setLongitude);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getLocationsId() {
		return _locationsId;
	}

	@Override
	public void setLocationsId(long locationsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locationsId = locationsId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public double getLatitude() {
		return _latitude;
	}

	@Override
	public void setLatitude(double latitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_latitude = latitude;
	}

	@JSON
	@Override
	public double getLongitude() {
		return _longitude;
	}

	@Override
	public void setLongitude(double longitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_longitude = longitude;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), locations.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public locations toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, locations>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		locationsImpl locationsImpl = new locationsImpl();

		locationsImpl.setLocationsId(getLocationsId());
		locationsImpl.setGroupId(getGroupId());
		locationsImpl.setCompanyId(getCompanyId());
		locationsImpl.setUserId(getUserId());
		locationsImpl.setUserName(getUserName());
		locationsImpl.setCreateDate(getCreateDate());
		locationsImpl.setModifiedDate(getModifiedDate());
		locationsImpl.setName(getName());
		locationsImpl.setLatitude(getLatitude());
		locationsImpl.setLongitude(getLongitude());

		locationsImpl.resetOriginalValues();

		return locationsImpl;
	}

	@Override
	public locations cloneWithOriginalValues() {
		locationsImpl locationsImpl = new locationsImpl();

		locationsImpl.setLocationsId(
			this.<Long>getColumnOriginalValue("locationsId"));
		locationsImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		locationsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		locationsImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		locationsImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		locationsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		locationsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		locationsImpl.setName(this.<String>getColumnOriginalValue("name"));
		locationsImpl.setLatitude(
			this.<Double>getColumnOriginalValue("latitude"));
		locationsImpl.setLongitude(
			this.<Double>getColumnOriginalValue("longitude"));

		return locationsImpl;
	}

	@Override
	public int compareTo(locations locations) {
		long primaryKey = locations.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof locations)) {
			return false;
		}

		locations locations = (locations)object;

		long primaryKey = locations.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<locations> toCacheModel() {
		locationsCacheModel locationsCacheModel = new locationsCacheModel();

		locationsCacheModel.locationsId = getLocationsId();

		locationsCacheModel.groupId = getGroupId();

		locationsCacheModel.companyId = getCompanyId();

		locationsCacheModel.userId = getUserId();

		locationsCacheModel.userName = getUserName();

		String userName = locationsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			locationsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			locationsCacheModel.createDate = createDate.getTime();
		}
		else {
			locationsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			locationsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			locationsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		locationsCacheModel.name = getName();

		String name = locationsCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			locationsCacheModel.name = null;
		}

		locationsCacheModel.latitude = getLatitude();

		locationsCacheModel.longitude = getLongitude();

		return locationsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<locations, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<locations, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<locations, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((locations)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, locations>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					locations.class, ModelWrapper.class);

	}

	private long _locationsId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private double _latitude;
	private double _longitude;

	public <T> T getColumnValue(String columnName) {
		Function<locations, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((locations)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("locationsId", _locationsId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("latitude", _latitude);
		_columnOriginalValues.put("longitude", _longitude);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("locationsId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("name", 128L);

		columnBitmasks.put("latitude", 256L);

		columnBitmasks.put("longitude", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private locations _escapedModel;

}